export default{
        sector: "Sector",
        sectorvalue: false,
        sectorComments: "",
        company: "Company Name",
        companyvalue: false,
        companyComments: "",
        model: "Business model, product and services",
        modelvalue: false,
        modelComments: "",
        popularity: "Popularity",
        popularityvalue: false,
        popularityComments: "",
        competitors: "Competitors",
        competitorsvalue: false,
        competitorsComments: "",
        review: "Company self and competitor reviews",
        reviewvalue: false,
        reviewComments: "",
        how: "Customer satisfaction",
        howvalue: false,
        howComments: "",
        location: "Locations of business",
        locationsvalue: false,
        locationsComments: "",
        shareholders: "Major shareholders",
        shareholdersvalue: false,
        shareholdersComments: "",
        subsidiaries: "Subsidiaries",
        subsidiariesvalue: false,
        subsidiariesComments: "",
        risks: "Risks on recession, pandemic and latest tech",
        risksvalue: false,
        risksComments: "",
}   
