export default{
        sector: "Sector",
        sectorComments: "",
        company: "Company Name",
        companyComments: "",
        model: "Business model, product and services",
        modelComments: "",
        popularity: "Popularity",
        popularityComments: "",
        competitors: "Competitors",
        competitorsComments: "",
        review: "Company self and competitor reviews",
        reviewComments: "",
        how: "Customer satisfaction",
        howComments: "",
        location: "Locations of business",
        locationsComments: "",
        shareholders: "Major shareholders",
        shareholdersComments: "",
        subsidiaries: "Subsidiaries",
        subsidiariesComments: "",
        risks: "Risks on recession, pandemic and latest tech",
        risksComments: "",
}   
